### PR TITLE
[CSB-1149] Manages narayana-spring-boot-starter version

### PR DESCRIPTION
**Pull request by mcarlett**

### CODE REVIEW

**Comment by cunningt** [comment]
Do we need to add this?   I'm looking at the previous releases - in 3.14.5 and 3.18.3, we did not have it listed 

https://github.com/jboss-fuse/camel-spring-boot/blob/camel-spring-boot-3.18.3-branch/pom.xml#L148-L166
https://github.com/jboss-fuse/camel-spring-boot/blob/camel-spring-boot-3.14.5-branch/pom.xml#L172-L182

The BOM and dependencies generators I think add narayana-spring-boot-starter to the BOM/dependencies, I'm not sure if adding it will duplicate entries.

**Review by Croway — APPROVED** [review]

**Comment by Croway** [comment]
yeah,  probably this commit https://github.com/jboss-fuse/camel-spring-boot/blob/camel-spring-boot-3.18.3-branch/tooling/camel-spring-boot-generator-maven-plugin/src/main/java/org/apache/camel/springboot/maven/BomDependenciesGeneratorMojo.java#L312  is missing, could it be @cunningt ? in case, do we have a list of all  the commits that need to be applied whenever we change a version?

**Comment by mcarlett** [comment]
> Do we need to add this? I'm looking at the previous releases - in 3.14.5 and 3.18.3, we did not have it listed
> 
> https://github.com/jboss-fuse/camel-spring-boot/blob/camel-spring-boot-3.18.3-branch/pom.xml#L148-L166 https://github.com/jboss-fuse/camel-spring-boot/blob/camel-spring-boot-3.14.5-branch/pom.xml#L172-L182
> 
> The BOM and dependencies generators I think add narayana-spring-boot-starter to the BOM/dependencies, I'm not sure if adding it will duplicate entries.

I agree @cunningt but I would like to know if we should drop other dependencies management (narayana-spring-boot-core and narayana-spring-boot-recovery-controller) https://github.com/jboss-fuse/camel-spring-boot/blob/camel-spring-boot-3.20.1-branch/pom.xml#L155-L164

**Comment by mcarlett** [comment]
narayana dependencies are managed here https://github.com/jboss-fuse/camel-spring-boot/pull/145

**Pull request closed without merging**
