### PR TITLE
fetch and add agroal version to CSB bom

### PR DESCRIPTION
**Pull request by rinaldodev**

### CODE REVIEW

**Review by Croway — APPROVED** [review]

**Review by cunningt — APPROVED** [review]

**Comment by cunningt** [comment]
@rinaldodev I don't see any issue with this going into the next 4.4.0 patch - @Croway do you think this is okay?

**Comment by Croway** [comment]
that's fine, but it is important that it get backported in 4.8

**Comment by rinaldodev** [comment]
@cunningt can we trigger a rerun? I don't see how the current error is related to the changes in this PR.

**Comment by cunningt** [comment]
@rinaldodev Do you mind rebasing?   I think the error here was fixed underneath, should clear up after a rebase

**Comment by rinaldodev** [comment]
@cunningt done

**Pull request merged**
